# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Angry-Bender's blog house
locale : "en-AU"
#email:
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog on various topics. I aim to do a few write-ups here based on my experience as a systems administrator & cyber security professional
#twitter_username: username
github_username: angry-bender
url: "https://angry-bender.github.io"
repository: "NWO/angry-bender.github.io"

minimal_mistakes_skin: dark
search: true
teaser: /img/angrybender.png
logo: "https://media.giphy.com/media/tNC2rod1uTrdC/giphy.gif"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "Angry Bender"
  avatar : "/img/angrybender.png"
  bio    : "Hi there, its good to see you"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/angry-bender"
    - label: "Reddit"
      icon: "fab fa-reddit-alien"
      url: "https://www.reddit.com/user/angrybender/"
    - label: "Hack The Box (Its been a while)"
      icon: "fas fa-cube"
      url: "https://www.hackthebox.eu/home/users/profile/84498"
    
footer:
  links:

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide 
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
      toc: false
      toc_icon: fas fa-clipboard-list
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      classes: wide 
      author_profile: false
      share: true
      related: true
      

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
